### ISSUE TITLE
Nollup not guessing output.globals names

### ISSUE THREAD

**Issue by afialapis** [PepsRyuu/nollup#236]
Hi,

I guess this is not a problem but something expected. But I would like to understand reasons behind.

When using `external` option, we need to set also `output.globals`.
A common example may be this:

```
{
  input: './index.js',
  output: {
    file: './dist/bundle.js',
    format: 'iife',
    globals: {
      'react': 'React',
      'react-dom': 'ReactDOM'
    }
  },
  external: ['react', 'react-dom'],
  plugins: [
    ...
  ]
}
```

If I use a plugin like [rollup-plugin-node-externals](https://github.com/Septh/rollup-plugin-node-externals), I get the `external` option automatically filled. But not the `output.globals`.

```
import {externals} from 'rollup-plugin-node-externals'
{
  input: './index.js',
  output: {
    file: './dist/bundle.js',
    format: 'iife'
  },
  plugins: [
    ...
    externals()
  ]
}
```

Rollup will show this warning:

```
(!) Missing global variable names
Use output.globals to specify browser global variable names corresponding to external modules
react (guessing 'React')
react-dom (guessing 'ReactDOM')
```

But, thing is, Rollup do guess the global names, and things just work. While Nollup does not make this guessing, so things won't work.

· Why does not Nollup do this guessing? 

· I see the way Rollup does this guessing (probably) [is around here](https://github.com/rollup/rollup/blob/27c0557f904321d649c9bd85f6fb670ca5700427/src/Chunk.ts#L1419). ¿Does it exist an standard way to extract the global name/s from a module? ¿Or maybe there is some Rollup call for it? My main intention is to make some tool to automatically fill `output.globals` along with `externals` (as long as it makes sense!).

Thanks for your time and help!

P.S: I've created the repo [test-nollup-with-externals](https://github.com/afialapis/test-nollup-with-externals) for you to play, if you want.

**Comment by PepsRyuu** [comment]
This is the line in question here: https://github.com/PepsRyuu/nollup/blob/master/lib/impl/NollupCodeGenerator.js#L119

Just need to replace the ```|| name``` with a proper implementation. Shouldn't be too difficult. Let me see what I can do. 🙂

**Comment by PepsRyuu** [comment]
Fixed in ```0.20.0```.

**Comment by afialapis** [comment]
Wow, I really appreciate the fast answer and intervention. Thanks!
I've tested it but in my case, problem persists (for react, we do get `react` instead of `React`):
```
var __nollup__external__react__default__ = self.self.react && self.react.hasOwnProperty('default')? self.react.default : self.react;
```
I guess `getIIFEName()` would be the place to touch, but, is it really a naming convention this TitleCase for global names?

Thanks again for your time. I do get a bit lost with all this import/export default/no default cjs/esm stuff, so sorry in advance if I'm getting in detail in nonsense stuff or taking wrong approaches.

**Comment by PepsRyuu** [comment]
For some reason I was too focused on how special characters were treated, it slipped my mind to try something as simple as "React". 😂 Looking into it, it looks like I also need to check how the import is actually used:

```
import React from "react"; 
```

Since we import as ```React```, it needs to prefer that, and then if that doesn't work use the auto-guess.

**Comment by PepsRyuu** [comment]
Have a version of it working, will publish later this evening or tomorrow, whenever I get the chance. :)

**Comment by PepsRyuu** [comment]
Fixed in ```0.20.1```.

**Comment by afialapis** [comment]
Fantastic. Super thanks!
